### ISSUE TITLE
Discovery intermittently crashes

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5018]
## What went wrong? 😲

An issue with [astro-dnssd](https://github.com/AstroHQ/astro-dnssd) crate causing OMS server to crash when ~~running two instances from the same machine (ie central server OMS + local OMS).~~

Edit: happening with only one instance now!

## How to Reproduce 🔨

Reproduction or error is intermittent, and might not always panic. 

Steps to reproduce the behaviour:

1. Run OMS
3. See error, ie:

```
2024-10-07 12:26:26.495206000 [INFO] <astro_dnssd::os::apple::register:44>:Got reply
thread '<unnamed>' panicked at /Users/fergusroache/.cargo/registry/src/index.crates.io-6f17d22bba15001f/astro-dnssd-0.3.4/src/os/apple/register.rs:77:40:
called `Result::unwrap()` on an `Err` value: SendError { .. }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
```

Probably occuring as a result of unwrapping the error in astro-dnssd crate:

```
            Ok((name, regtype, domain)) => {
                if error_code == kDNSServiceErr_NoError {
                    let reply = DNSServiceRegisterReply {
                        regtype,
                        name,
                        domain,
                    };
                    tx.send(Ok(reply)).unwrap();
                    info!("Reply info sent");
                } else {
                    error!("Error in reply: {}", error_code);
                    tx.send(Err(RegistrationError::ServiceError(error_code)))
                        .unwrap();
                }
            }
```

## Your environment 🌱

- Open mSupply Version: Develop (but occuring on main / 2.3.0 also)

**Comment by fergie-nz** [comment]
Note - reverting my version of rust from 1.81 to 1.80 seems to have fixed this for me. No longer panicking

**Comment by lache-melvin** [comment]
I have also been seeing this issue, though I've only had the thread panic logged, the app continues to run. I'm on 1.79.0 though. We might need to look into dependency upgrades?

**Comment by andreievg** [comment]
Could be a quick fix with configuration, low severity but can be upped in priority since it's not that much work

**Comment by lache-melvin** [comment]
See #5389 - it's getting worse 😱

**Comment by andreievg** [comment]
Launch in new process and allow to crash

**Comment by roxy-dao** [comment]
Maybe using a new crate might work better? https://docs.rs/async-dnssd/latest/async_dnssd/ will need other changes tho

**Comment by lache-melvin** [comment]
@noel-yeldos is this still crashing the app after @jmbrunskill's change last week, or is this panic logged, and then app continues?

**Comment by noel-yeldos** [comment]
> [@noel-yeldos](https://github.com/noel-yeldos) is this still crashing the app after [@jmbrunskill](https://github.com/jmbrunskill)'s change last week, or is this panic logged, and then app continues?

@lache-melvin The former. App crashes and doesn't continue. I created a new branch off develop this morning. I assume James' fix was merged into develop?

**Comment by lache-melvin** [comment]
Yeah it was... hm, I wonder if it's worth you trying to downgrade to 1.81? I think that's what most people are on right now and I haven't heard any issues, interesting that the fix isn't working with 1.84 though 👀

**Comment by jmbrunskill** [comment]
I think this was Andrei's concern for some reason the `catch_panic` isn't working. We might need to go back to the option of disabling discovery via the configuration  file I think.

**Comment by noel-yeldos** [comment]
![Image](https://github.com/user-attachments/assets/67ec41f3-1747-457c-be53-91841589c255)

![Image](https://github.com/user-attachments/assets/9ead2f72-8003-4c39-9f93-6709249183ff)

I've downgraded to 1.81. Still panicking :(
